/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jjayaku1.crud.restcl.ui;

import javax.swing.JFrame;
import com.jjayaku1.crud.restcl.*;
import com.jjayaku1.crud.jaxb.model.*;
import com.jjayaku1.crud.restcl.jaxb.utils.*;
import com.sun.jersey.api.client.ClientResponse;

/**
 *
 * @author hp pc
 */
public class GradeBookForm extends javax.swing.JFrame {

    private static final GradeDetailsCrud restClient = new GradeDetailsCrud();
    private static String selectedAction = "";

    /**
     * Creates new form GradeBookForm
     */
    public GradeBookForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        createGradeItemRadio = new javax.swing.JRadioButton();
        updateGradeItemRadio = new javax.swing.JRadioButton();
        getGradeItemRadio = new javax.swing.JRadioButton();
        deleteGradeItemRadio = new javax.swing.JRadioButton();
        addStudentGradeRadio = new javax.swing.JRadioButton();
        updateStudentGradeRadio = new javax.swing.JRadioButton();
        getStudentGradeRadio = new javax.swing.JRadioButton();
        deleteStudentGradeRadio = new javax.swing.JRadioButton();
        gradeItemInputPanel = new javax.swing.JPanel();
        lblGradeItemName = new javax.swing.JLabel();
        lblGradeItemWeight = new javax.swing.JLabel();
        txtGradeItemName = new javax.swing.JTextField();
        txtGradeItemWeight = new javax.swing.JTextField();
        btnGradeItemSubmit = new javax.swing.JButton();
        lblGradeItemId = new javax.swing.JLabel();
        txtItemId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResult = new javax.swing.JTextArea();
        gradePanel = new javax.swing.JPanel();
        lblStudentName = new javax.swing.JLabel();
        lblGradeItemNameGrade = new javax.swing.JLabel();
        lblStudentGrade = new javax.swing.JLabel();
        lblInstructorFeedback = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtGradeItemNameGrade = new javax.swing.JTextField();
        txtStudentGrade = new javax.swing.JTextField();
        txtInstructorFeedback = new javax.swing.JTextField();
        btnGradeSubmit = new javax.swing.JButton();
        panelgradeResult = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaResult1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(createGradeItemRadio);
        createGradeItemRadio.setText("Create Grade Item");
        createGradeItemRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGradeItemRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(updateGradeItemRadio);
        updateGradeItemRadio.setText("Update Grade Item");
        updateGradeItemRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGradeItemRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(getGradeItemRadio);
        getGradeItemRadio.setText("Get Grade Item");
        getGradeItemRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getGradeItemRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(deleteGradeItemRadio);
        deleteGradeItemRadio.setText("Delete Grade Item");
        deleteGradeItemRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGradeItemRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(addStudentGradeRadio);
        addStudentGradeRadio.setText("Add Student Grade");
        addStudentGradeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentGradeRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(updateStudentGradeRadio);
        updateStudentGradeRadio.setText("Update Student Grade");
        updateStudentGradeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentGradeRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(getStudentGradeRadio);
        getStudentGradeRadio.setText("Get Student Grade");
        getStudentGradeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStudentGradeRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(deleteStudentGradeRadio);
        deleteStudentGradeRadio.setText("Delete Student Grade");
        deleteStudentGradeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentGradeRadioActionPerformed(evt);
            }
        });

        lblGradeItemName.setText("Grade Item Name");

        lblGradeItemWeight.setText("Grade Item Weight");

        txtGradeItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeItemNameActionPerformed(evt);
            }
        });

        btnGradeItemSubmit.setText("Submit");
        btnGradeItemSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeItemSubmitActionPerformed(evt);
            }
        });

        lblGradeItemId.setText("Grade Item Id");

        txtAreaResult.setColumns(20);
        txtAreaResult.setRows(5);
        jScrollPane1.setViewportView(txtAreaResult);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout gradeItemInputPanelLayout = new javax.swing.GroupLayout(gradeItemInputPanel);
        gradeItemInputPanel.setLayout(gradeItemInputPanelLayout);
        gradeItemInputPanelLayout.setHorizontalGroup(
            gradeItemInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradeItemInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradeItemInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gradeItemInputPanelLayout.createSequentialGroup()
                        .addGroup(gradeItemInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGradeItemName)
                            .addComponent(lblGradeItemWeight)
                            .addComponent(lblGradeItemId))
                        .addGap(36, 36, 36)
                        .addGroup(gradeItemInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGradeItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(txtGradeItemWeight)
                            .addComponent(btnGradeItemSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtItemId))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        gradeItemInputPanelLayout.setVerticalGroup(
            gradeItemInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradeItemInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradeItemInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeItemName)
                    .addComponent(txtGradeItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradeItemInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeItemWeight)
                    .addComponent(txtGradeItemWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradeItemInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeItemId)
                    .addComponent(txtItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnGradeItemSubmit)
                .addGap(47, 47, 47)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        lblStudentName.setText("Student Id");

        lblGradeItemNameGrade.setText("Grade Item Name");

        lblStudentGrade.setText("Student Grade");

        lblInstructorFeedback.setText("Instructor Feedback");

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        btnGradeSubmit.setText("Submit");
        btnGradeSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeSubmitActionPerformed(evt);
            }
        });

        txtAreaResult1.setColumns(20);
        txtAreaResult1.setRows(5);
        jScrollPane2.setViewportView(txtAreaResult1);

        javax.swing.GroupLayout panelgradeResultLayout = new javax.swing.GroupLayout(panelgradeResult);
        panelgradeResult.setLayout(panelgradeResultLayout);
        panelgradeResultLayout.setHorizontalGroup(
            panelgradeResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelgradeResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelgradeResultLayout.setVerticalGroup(
            panelgradeResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelgradeResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout gradePanelLayout = new javax.swing.GroupLayout(gradePanel);
        gradePanel.setLayout(gradePanelLayout);
        gradePanelLayout.setHorizontalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradePanelLayout.createSequentialGroup()
                        .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStudentName)
                            .addComponent(lblGradeItemNameGrade)
                            .addComponent(lblStudentGrade))
                        .addGap(31, 31, 31)
                        .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGradeItemNameGrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtStudentGrade)
                            .addComponent(txtStudentName)))
                    .addGroup(gradePanelLayout.createSequentialGroup()
                        .addComponent(lblInstructorFeedback)
                        .addGap(18, 18, 18)
                        .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGradeSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInstructorFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradePanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(panelgradeResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        gradePanelLayout.setVerticalGroup(
            gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentName)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGradeItemNameGrade)
                    .addComponent(txtGradeItemNameGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentGrade)
                    .addComponent(txtStudentGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gradePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstructorFeedback)
                    .addComponent(txtInstructorFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGradeSubmit)
                .addGap(43, 43, 43)
                .addComponent(panelgradeResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteStudentGradeRadio)
                    .addComponent(getStudentGradeRadio)
                    .addComponent(addStudentGradeRadio)
                    .addComponent(updateStudentGradeRadio)
                    .addComponent(createGradeItemRadio)
                    .addComponent(updateGradeItemRadio)
                    .addComponent(getGradeItemRadio)
                    .addComponent(deleteGradeItemRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(gradeItemInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createGradeItemRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateGradeItemRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getGradeItemRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteGradeItemRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addStudentGradeRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateStudentGradeRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getStudentGradeRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteStudentGradeRadio))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(gradeItemInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gradePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(327, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Instructor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateGradeItemRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGradeItemRadioActionPerformed
        // TODO add your handling code here:
        selectedAction = "UpdateGradeItem";
        this.gradeItemInputPanel.setVisible(true);
        this.gradePanel.setVisible(false);
        lblGradeItemId.setVisible(true);
        txtItemId.setVisible(true);
        lblGradeItemName.setVisible(true);
        lblGradeItemWeight.setVisible(true);
        txtGradeItemName.setVisible(true);
        txtGradeItemWeight.setVisible(true);
        txtAreaResult.setText("");
    }//GEN-LAST:event_updateGradeItemRadioActionPerformed

    private void getGradeItemRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getGradeItemRadioActionPerformed
        // TODO add your handling code here:
        selectedAction = "GetGradeItem";
        this.gradeItemInputPanel.setVisible(true);
        lblGradeItemId.setVisible(true);
        txtItemId.setVisible(true);
        this.gradePanel.setVisible(false);
        lblGradeItemName.setVisible(false);
        lblGradeItemWeight.setVisible(false);
        txtGradeItemName.setVisible(false);
        txtGradeItemWeight.setVisible(false);
        txtAreaResult.setText("");
    }//GEN-LAST:event_getGradeItemRadioActionPerformed

    private void deleteGradeItemRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGradeItemRadioActionPerformed
        // TODO add your handling code here:
        selectedAction = "DeleteGradeItem";
        this.gradeItemInputPanel.setVisible(true);
        lblGradeItemId.setVisible(true);
        txtItemId.setVisible(true);
        this.gradePanel.setVisible(false);
        lblGradeItemName.setVisible(false);
        lblGradeItemWeight.setVisible(false);
        txtGradeItemName.setVisible(false);
        txtGradeItemWeight.setVisible(false);
        txtAreaResult.setText("");
    }//GEN-LAST:event_deleteGradeItemRadioActionPerformed

    private void addStudentGradeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentGradeRadioActionPerformed
        // TODO add your handling code here:
        selectedAction = "AddGrade";
        this.gradeItemInputPanel.setVisible(false);
        this.gradePanel.setVisible(true);
        lblStudentName.setVisible(true);
        txtStudentName.setVisible(true);
        lblGradeItemNameGrade.setVisible(true);
        txtGradeItemNameGrade.setVisible(true);
        lblStudentGrade.setVisible(true);
        txtStudentGrade.setVisible(true);
        lblInstructorFeedback.setVisible(true);
        txtInstructorFeedback.setVisible(true);
        txtAreaResult1.setText("");
    }//GEN-LAST:event_addStudentGradeRadioActionPerformed

    private void createGradeItemRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGradeItemRadioActionPerformed
        // TODO add your handling code here:
        selectedAction = "CreateGradeItem";
        this.gradeItemInputPanel.setVisible(true);
        this.gradePanel.setVisible(false);
        lblGradeItemId.setVisible(false);
        txtItemId.setVisible(false);
        lblGradeItemName.setVisible(true);
        lblGradeItemWeight.setVisible(true);
        txtGradeItemName.setVisible(true);
        txtGradeItemWeight.setVisible(true);
        txtAreaResult.setText("");
    }//GEN-LAST:event_createGradeItemRadioActionPerformed

    private void txtGradeItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradeItemNameActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void btnGradeSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeSubmitActionPerformed
        // TODO add your handling code here:
        if(selectedAction.equals("AddGrade")){
            GradeBookEntry newObj = new GradeBookEntry();
            newObj.setStudentId(Long.parseLong(txtStudentName.getText()));
            newObj.setFeedBack(txtInstructorFeedback.getText());
            newObj.setGrade(Double.parseDouble(txtStudentGrade.getText()));
            newObj.setItemName(txtGradeItemNameGrade.getText());
            
            String xmlString = Converter.convertFromObjectToXml(newObj, GradeBookEntry.class);
            ClientResponse clientResponse = restClient.createGradeEntryResource(xmlString);
            txtAreaResult1.setText(clientResponse.toString() + "   is the result");
            
        }
        else if(selectedAction.equals("UpdateGrade")){
           GradeBookEntry newObj = new GradeBookEntry();
            newObj.setStudentId(Long.parseLong(txtStudentName.getText()));
            newObj.setFeedBack(txtInstructorFeedback.getText());
            newObj.setGrade(Double.parseDouble(txtStudentGrade.getText()));
            newObj.setItemName(txtGradeItemNameGrade.getText());
            String xmlString = Converter.convertFromObjectToXml(newObj, GradeBookEntry.class);
            ClientResponse clientResponse = restClient.updateGradeEntryResource(xmlString,txtStudentName.getText());
            txtAreaResult1.setText(clientResponse.toString() + "   is the result");
            
        }
        else if(selectedAction.equals("GetGrade")){
            ClientResponse clientResponse = restClient.getGradeEntryResource(ClientResponse.class, txtStudentName.getText());
            txtAreaResult1.setText(clientResponse.toString()+" is the result");
        }
        else if(selectedAction.equals("DeleteAllGrades")){
            ClientResponse clientResponse = restClient.deleteAllGradeEntry(txtStudentName.getText());
            txtAreaResult1.setText(clientResponse.toString()+" is the result");
        }
        else if(selectedAction.equals("DeleteOneGrade")){
            
        }
    }//GEN-LAST:event_btnGradeSubmitActionPerformed

    private void updateStudentGradeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentGradeRadioActionPerformed
        // TODO add your handling code here:
        selectedAction = "UpdateGrade";
        this.gradeItemInputPanel.setVisible(false);
        this.gradePanel.setVisible(true);
        lblStudentName.setVisible(true);
        txtStudentName.setVisible(true);
        lblGradeItemNameGrade.setVisible(true);
        txtGradeItemNameGrade.setVisible(true);
        lblStudentGrade.setVisible(true);
        txtStudentGrade.setVisible(true);
        lblInstructorFeedback.setVisible(true);
        txtInstructorFeedback.setVisible(true);
        txtAreaResult1.setText("");
    }//GEN-LAST:event_updateStudentGradeRadioActionPerformed

    private void getStudentGradeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStudentGradeRadioActionPerformed
        // TODO add your handling code here:
        selectedAction = "GetGrade";
        this.gradeItemInputPanel.setVisible(false);
        this.gradePanel.setVisible(true);
        lblStudentName.setVisible(true);
        txtStudentName.setVisible(true);
        lblGradeItemNameGrade.setVisible(false);
        txtGradeItemNameGrade.setVisible(false);
        lblStudentGrade.setVisible(false);
        txtStudentGrade.setVisible(false);
        lblInstructorFeedback.setVisible(false);
        txtInstructorFeedback.setVisible(false);
        txtAreaResult1.setText("");
    }//GEN-LAST:event_getStudentGradeRadioActionPerformed

    private void deleteStudentGradeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentGradeRadioActionPerformed
        // TODO add your handling code here:
        selectedAction = "DeleteAllGrades";
        this.gradeItemInputPanel.setVisible(false);
        this.gradePanel.setVisible(true);
        lblStudentName.setVisible(true);
        txtStudentName.setVisible(true);
        lblGradeItemNameGrade.setVisible(false);
        txtGradeItemNameGrade.setVisible(false);
        lblStudentGrade.setVisible(false);
        txtStudentGrade.setVisible(false);
        lblInstructorFeedback.setVisible(false);
        txtInstructorFeedback.setVisible(false);
        txtAreaResult1.setText("");
    }//GEN-LAST:event_deleteStudentGradeRadioActionPerformed

    private void btnGradeItemSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeItemSubmitActionPerformed
        // TODO add your handling code here:
        if (selectedAction.equals("CreateGradeItem")) {
            GradeItem newObj = new GradeItem();
            newObj.setItemName(txtGradeItemName.getText());
            newObj.setItemWeight(Double.parseDouble(txtGradeItemWeight.getText()));
            newObj.setItemId(-1);
            String xmlString = Converter.convertFromObjectToXml(newObj, GradeItem.class);
            ClientResponse clientResponse = restClient.createGradeItemResource(xmlString);
            txtAreaResult.setText(clientResponse.toString() + "   is the result");

        } else if (selectedAction.equals("UpdateGradeItem")) {
            GradeItem newObj = new GradeItem();
            newObj.setItemName(txtGradeItemName.getText());
            newObj.setItemWeight(Double.parseDouble(txtGradeItemWeight.getText()));
            newObj.setItemId(Integer.parseInt(txtItemId.getText()));
            String xmlString = Converter.convertFromObjectToXml(newObj, GradeItem.class);
            ClientResponse clientResponse = restClient.updateGradeItemResource(xmlString, txtItemId.getText());
            txtAreaResult.setText(clientResponse.toString() + "   is the result");
            
        }
        else if(selectedAction.equals("GetGradeItem")){
            
            ClientResponse clientResponse = restClient.getGradeItemResource(ClientResponse.class, txtItemId.getText());
            txtAreaResult.setText(clientResponse.toString() + "   is the result");
            
        }
        else if(selectedAction.equals("DeleteGradeItem")){
            ClientResponse clientResponse = restClient.deleteGradeItem(txtItemId.getText());
            txtAreaResult.setText(clientResponse.toString());
        }
    }//GEN-LAST:event_btnGradeItemSubmitActionPerformed

    private void hidePanelsInitially() {
        lblGradeItemId.setVisible(false);
        txtItemId.setVisible(false);
        gradeItemInputPanel.setVisible(false);
        gradePanel.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        JFrame frame = new GradeBookForm();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                GradeBookForm frame = new GradeBookForm();
                frame.hidePanelsInitially();
                frame.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addStudentGradeRadio;
    private javax.swing.JButton btnGradeItemSubmit;
    private javax.swing.JButton btnGradeSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton createGradeItemRadio;
    private javax.swing.JRadioButton deleteGradeItemRadio;
    private javax.swing.JRadioButton deleteStudentGradeRadio;
    private javax.swing.JRadioButton getGradeItemRadio;
    private javax.swing.JRadioButton getStudentGradeRadio;
    private javax.swing.JPanel gradeItemInputPanel;
    private javax.swing.JPanel gradePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblGradeItemId;
    private javax.swing.JLabel lblGradeItemName;
    private javax.swing.JLabel lblGradeItemNameGrade;
    private javax.swing.JLabel lblGradeItemWeight;
    private javax.swing.JLabel lblInstructorFeedback;
    private javax.swing.JLabel lblStudentGrade;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JPanel panelgradeResult;
    private javax.swing.JTextArea txtAreaResult;
    private javax.swing.JTextArea txtAreaResult1;
    private javax.swing.JTextField txtGradeItemName;
    private javax.swing.JTextField txtGradeItemNameGrade;
    private javax.swing.JTextField txtGradeItemWeight;
    private javax.swing.JTextField txtInstructorFeedback;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtStudentGrade;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JRadioButton updateGradeItemRadio;
    private javax.swing.JRadioButton updateStudentGradeRadio;
    // End of variables declaration//GEN-END:variables
}
